/*
 * Copyright 2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ml4j.nn.models.yolov2;

import java.io.IOException;

import org.ml4j.nn.FeedForwardNeuralNetworkContext;
import org.ml4j.nn.supervised.SupervisedFeedForwardNeuralNetwork;

/**
 * Interface for a factory for a Yolo V2 Network
 * 
 * @author Michael Lavelle
 *
 */
public interface YOLOv2Factory {

	/**
	 * Create a new Yolo V2 Network.
	 * 
	 * @param context The training or prediction context with which to construct
	 *                this network. This method may perform additional
	 *                configurations of this config during execution.
	 * @return A Yolo V2 Network
	 * @throws IOException In the event that the network cannot be loaded
	 */
	SupervisedFeedForwardNeuralNetwork createYoloV2(FeedForwardNeuralNetworkContext context) throws IOException;

	/**
	 * @return The labels for the Yolo V2 instances generated by this factory.
	 * @throws IOException In the event that the labels cannot be loaded
	 */
	YOLOv2Labels createYoloV2Labels() throws IOException;
}
